#include "Plugin.hpp"

#include <cstring>

#include "Core/SdlManager.hpp"

START_NAMESPACE_DISTRHO

std::atomic<int> GameControllerMIDIPlugin::sInstanceCount(0);

GameControllerMIDIPlugin::GameControllerMIDIPlugin()
    : Plugin(kParamCount, 0, 0) {
    int count = ++sInstanceCount;
    if (count > 1) {
        d_stderr2("WARNING: Multiple Plugin instances detected (%d)! This plugin is designed for a single instance only.", count);
    }
    // Create the dispatcher (owned by this plugin)
    fDispatcher = std::make_unique<GCMidi::EventDispatcher>();
    // Register with the global SDL pump
    GCMidi::SdlManager::getInstance().setEventHandler(fDispatcher.get());
}

GameControllerMIDIPlugin::~GameControllerMIDIPlugin() {
    // Unregister before destruction
    GCMidi::SdlManager::getInstance().setEventHandler(nullptr);
    sInstanceCount--;
}

void GameControllerMIDIPlugin::initParameter(uint32_t index, Parameter& parameter) {
    if (index == kParamOctave) {
        parameter.hints = kParameterIsAutomatable | kParameterIsInteger;
        parameter.name = "Octave";
        parameter.symbol = "octave";
        parameter.ranges.def = 0.0f;
        parameter.ranges.min = -4.0f;
        parameter.ranges.max = 4.0f;
    }
}

float GameControllerMIDIPlugin::getParameterValue(uint32_t index) const {
    if (index == kParamOctave && fDispatcher) {
        if (auto mapper = fDispatcher->getMapper()) {
            return (float)mapper->getOctaveOffset();
        }
    }
    return 0.0f;
}

void GameControllerMIDIPlugin::setParameterValue(uint32_t index, float value) {
    if (index == kParamOctave && fDispatcher) {
        if (auto mapper = fDispatcher->getMapper()) {
            mapper->setOctaveOffset((int)value);
        }
    }
}

void GameControllerMIDIPlugin::run(
    const float**,
    float**,
    uint32_t,
    const MidiEvent* midiEvents,
    uint32_t midiEventCount
) {
    // 0. Check for parameter changes from within the dispatcher (e.g. D-Pad octave change)
    if (fDispatcher && fDispatcher->getAndResetOctaveDirty()) {
        if (auto mapper = fDispatcher->getMapper()) {
            requestParameterValueChange(
                kParamOctave,
                (float)mapper->getOctaveOffset()
            );
        }
    }

    // 1. Process host MIDI
    for (uint32_t i = 0; i < midiEventCount; ++i) {
        writeMidiEvent(midiEvents[i]);
    }

    // 2. Poll MIDI from dispatcher (generated by SDL thread)
    if (fDispatcher) {
        GCMidi::RawMidi rawEv;
        while (fDispatcher->popMidi(rawEv)) {
            MidiEvent ev;
            ev.frame = 0;
            ev.size = rawEv.size;
            ev.dataExt = nullptr;
            std::memcpy(ev.data, rawEv.data, ev.size);

            writeMidiEvent(ev);
        }
    }
}

Plugin* createPlugin() {
    return new GameControllerMIDIPlugin();
}

END_NAMESPACE_DISTRHO
