# bin2c.cmake - Convert a file to a C header with embedded data
#
# Usage: cmake -DINPUT_FILE=<file> -DOUTPUT_FILE=<header> -DVAR_NAME=<name> -P bin2c.cmake

file(READ "${INPUT_FILE}" FILE_CONTENTS)
string(LENGTH "${FILE_CONTENTS}" FILE_SIZE)

# Convert to hex array
file(READ "${INPUT_FILE}" HEX_CONTENTS HEX)
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1, " HEX_CONTENTS "${HEX_CONTENTS}")

# Generate header
file(WRITE "${OUTPUT_FILE}"
"// Auto-generated by bin2c.cmake - DO NOT EDIT
#pragma once

#include <cstddef>
#include <cstdint>

inline constexpr uint8_t ${VAR_NAME}_data[] = {
    ${HEX_CONTENTS}
};

inline constexpr size_t ${VAR_NAME}_size = ${FILE_SIZE};
")
